# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a distance matrix.
#'
#' @export
#'
#' @param M a matrix of locations.
#' @param cutoff the cutoff distance.
#' @param kernel (string) a kernel function.
#' @param dist_fn (string) a distance function.
#'
DistMatrix <- function(M, cutoff, kernel = "bartlett", dist_fn = "Haversine") {
    .Call('_ConleySE_DistMatrix', PACKAGE = 'ConleySE', M, cutoff, kernel, dist_fn)
}

#' Calculate the correlation matrix.
#'
#' @export
#'
#' @param M a matrix of locations
#' @param cutoff the cutoff distance
#' @param X the model matrix
#' @param e vector of residuals
#' @param n1 number of obs
#' @param k number of variables?
#' @param kernel (string) a kernel function
#' @param dist_fn (string) a distance function
#'
XeeXhC <- function(M, cutoff, X, e, n1, k, kernel = "bartlett", dist_fn = "Haversine") {
    .Call('_ConleySE_XeeXhC', PACKAGE = 'ConleySE', M, cutoff, X, e, n1, k, kernel, dist_fn)
}

#' Calculate the correlation matrix for a balanced panel.
#'
#' @export
#'
#' @param dmat the distance matrix
#' @param X the matrix of covariates
#' @param e the residuals
#' @param n1 the number of observations
#' @param k the number of covariates
#'
Bal_XeeXhC <- function(dmat, X, e, n1, k) {
    .Call('_ConleySE_Bal_XeeXhC', PACKAGE = 'ConleySE', dmat, X, e, n1, k)
}

#' Calculate the correlation matrix for a large model. Avoids creating a 
#' distance matrix in memory but is slower.
#'
#' @export
#'
#' @param M a matrix of locations
#' @param cutoff the cutoff distance
#' @param X the model matrix
#' @param e vector of residuals
#' @param n1 number of obs
#' @param k number of variables
#' @param kernel (string) a kernel function
#' @param dist_fn (string) a distance function
#'
XeeXhC_Lg <- function(M, cutoff, X, e, n1, k, kernel = "bartlett", dist_fn = "Haversine") {
    .Call('_ConleySE_XeeXhC_Lg', PACKAGE = 'ConleySE', M, cutoff, X, e, n1, k, kernel, dist_fn)
}

#' Calculate the correlation matrix.
#'
#' @export
#'
#' @param times vector of times
#' @param cutoff the cutoff distance
#' @param X the model matrix
#' @param e vector of residuals
#' @param n1 number of obs
#' @param k number of variables
#'
TimeDist <- function(times, cutoff, X, e, n1, k) {
    .Call('_ConleySE_TimeDist', PACKAGE = 'ConleySE', times, cutoff, X, e, n1, k)
}

